### ISSUE TITLE
PCI slot ID based xdma identification

### ISSUE THREAD

**Issue by realtimeradio** [realtimeradio/casperfpga#2]
When multiple FPGA cards are installed in a server, each can be interacted with using an xdma driver instance. These are enumerated as `/dev/xdma0*` for the first instance, `/dev/xdma1*` for the second instance, etc. (See https://github.com/realtimeradio/casperfpga/blob/0ee8f522450345da2b8cd3eb7a866a21c37f82ab/src/transport_localpcie.py#L45)

One can associate the "instance  number" of an xdma driver with a PCI slot enumeration by examining:

```
(py3-venv) cosmic@cosmic-fpga-0:~$ ls /sys/bus/pci/drivers/xdma/*/xdma/
'/sys/bus/pci/drivers/xdma/0000:3e:00.0/xdma/':
xdma0_c2h_0    xdma0_events_0  xdma0_events_10  xdma0_events_12  xdma0_events_14  xdma0_events_2  xdma0_events_4  xdma0_events_6  xdma0_events_8  xdma0_h2c_0  xdma0_user
xdma0_control  xdma0_events_1  xdma0_events_11  xdma0_events_13  xdma0_events_15  xdma0_events_3  xdma0_events_5  xdma0_events_7  xdma0_events_9  xdma0_h2c_1  xdma0_xvc

'/sys/bus/pci/drivers/xdma/0000:64:00.0/xdma/':
xdma1_c2h_0    xdma1_events_0  xdma1_events_10  xdma1_events_12  xdma1_events_14  xdma1_events_2  xdma1_events_4  xdma1_events_6  xdma1_events_8  xdma1_h2c_0  xdma1_user
xdma1_control  xdma1_events_1  xdma1_events_11  xdma1_events_13  xdma1_events_15  xdma1_events_3  xdma1_events_5  xdma1_events_7  xdma1_events_9  xdma1_h2c_1  xdma1_xvc

'/sys/bus/pci/drivers/xdma/0000:65:00.0/xdma/':
xdma2_c2h_0    xdma2_events_0  xdma2_events_10  xdma2_events_12  xdma2_events_14  xdma2_events_2  xdma2_events_4  xdma2_events_6  xdma2_events_8  xdma2_h2c_0  xdma2_user
xdma2_control  xdma2_events_1  xdma2_events_11  xdma2_events_13  xdma2_events_15  xdma2_events_3  xdma2_events_5  xdma2_events_7  xdma2_events_9  xdma2_h2c_1  xdma2_xvc

(py3-venv) cosmic@cosmic-fpga-0:~$ lspci | grep -i xilinx
3e:00.0 Serial controller: Xilinx Corporation Device 9011
64:00.0 Serial controller: Xilinx Corporation Device 9011
65:00.0 Serial controller: Xilinx Corporation Device 9011
```

Seemingly, by default xdma instances are assigned in order, starting with the lowest-numbered PCI slot. I don't know if this behaviour can be relied upon.

It would be nice if a user could connect to a board by PCI ID, or, if the PCIe REST server could be configured such that it has a hard map of zero-based FPGA card ID (a.k.a. `LocalPcieTransport.instance_id`) to physical cards. E.g., perhaps the REST server could be started with an optional argument like `--pci_slots 3e,64,65`, which would mean a user connection to `instance_id=1` would always get the xdma driver associated with PCIe card 0x64, regardless of what the underlying xdma instance ID is. Without such a mapping of ID->PCIe slot, or a user explicitly providing a PCIe slot at the time of connection, the system has a potential "mistaken FPGA identity" failure mode in the event that one of the FPGA cards fails to be recognized as an xdma driver target, or the xdma instances get assigned in an unexpected way.

Possibly there are ways other than interrogating `/sys/..../drivers/xdma/...` to figure out (or specify) which FPGA cards get assigned which xdma driver instances which could also be used to guard against mistaken FPGA identity.

**Comment by jack-h** [comment]
This now exists for the `RemotePcieTransport`  (thanks!).
Is it possible to also implement for `LocalPcieTransport`?

**Comment by radonnachie** [comment]
Can be closed I believe.

**Comment by realtimeradio** [comment]
> Can be closed I believe.

As in, this works for the Local client too?

**Comment by radonnachie** [comment]
I'll move the functionality down to that level 👍 I missed your prior request (:

**Comment by radonnachie** [comment]
Can close too IMO.
