### ISSUE TITLE
Program FPGAs on start of REST server

### ISSUE THREAD

**Issue by realtimeradio** [realtimeradio/casperfpga#5]
It would be useful to put all the FPGAs in a known state when the REST server starts, by providing a `.fpg` file to be programmed when the server starts. Given the server will start automatically at boot, I'm not sure whether this is best supplied via command line, or some fixed configuration file / fixed fpg location

**Comment by radonnachie** [comment]
`--program` flag will do this :) otherwise the fpg file is just parsed and set.
