### ISSUE TITLE
Prevent user from programming incompatible PCIe bitstream

### ISSUE THREAD

**Issue by realtimeradio** [realtimeradio/casperfpga#6]
An FPGA board, booted to a template firmware image, can only be programmed over PCI with new firmware images based on the same template.

Information about which template an fpg file was built against is contained in the fpg header:

```
?meta ADM_PCIE_9H7  xps:xsg pr_template [/home/jackh/src/vla-dev/pr_templates/adm_pcie_9h7_dts_dual_4x100g_pr_template-no-ip.xpr.zip]
```
So, at least up to any ambiguities based on file names, it would be possible to read this (by directly parsing the fpg header or interrogating CasperFpga to find device info) and check it matches what is already programmed. (Related to Issue #5)

**Comment by radonnachie** [comment]
Sure our primary use case is now the RemotePcieTransport, but this would also be applicable to the LocalPcieTransport right?

**Comment by realtimeradio** [comment]
That's trickier. With the REST server being a fairly static beast, it's sane for it to know what the boot image of the board is.
For the LocalPcieTransport, the user could tell it the template when they connect, which would allow the test for future reprograms, but I would imagine if the user is going to try to program the wrong thing, chances are they're going to assume the wrong template is the correct one anyway.

**Comment by radonnachie** [comment]
Yeah, I've implemented a `fpgfile` kwarg to the localpcie constructor, which then gets parsed for a `pr_template` value, defaulting to None. The fpgfile doesn't currently get programmed as part of the constructor (I think that if anything that should be triggered by another kwarg)... I'll also add that if a programming is successful and the `self.fpg_template is None`, then try parse the fpgfile just programmed for the template.

**Comment by realtimeradio** [comment]
Agree that programming as part of the constructor without a very explicit keyword would be bad.
Other than that, the best you can really do is make sure that:
1. If a template is provided, program calls are compatible with this
2. If a template is not provided, multiple programming calls are at least consistent with a common template

I take your comment to mean that this is basically what you've done(?)

I think anything more will need something smart baked into the firmware (there are magical PCI version registers which could be set/read and used for this) but smartness is in short supply at my end.

**Comment by radonnachie** [comment]
Correct, that's practically what I've done: #8

**Comment by realtimeradio** [comment]
Thanks!

**Comment by radonnachie** [comment]
Happily!
